<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AvaloniaVersion>11.3.2</AvaloniaVersion>
    <VersionPrefix>0.1.0</VersionPrefix>
  </PropertyGroup>
</Project>
