<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Edit.Editor.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Edit.Editor\Edit.Editor.csproj" />
  </ItemGroup>
</Project>
