<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Edit.Lsp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edit.Core\Edit.Core.csproj" />
    <ProjectReference Include="..\Edit.Text\Edit.Text.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
