<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Edit.TreeSitter\Edit.TreeSitter.csproj" />
    <ProjectReference Include="..\..\src\Edit.Text\Edit.Text.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\native\**\*" Link="native\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\native')" />
    <None Include="..\..\config\tree-sitter-grammars.json" Link="config\tree-sitter-grammars.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
