<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Edit.Core</RootNamespace>
    <AssemblyName>Edit.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edit.ComponentModel\Edit.ComponentModel.csproj" />
    <ProjectReference Include="..\Edit.Text\Edit.Text.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
