<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Edit.Plugins.Host</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edit.ComponentModel\Edit.ComponentModel.csproj" />
    <ProjectReference Include="..\Edit.Core\Edit.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
